services:
  adguardhome:
    container_name: adguard
    restart: unless-stopped
    volumes:
      - /docker/adguardhome:/opt/adguardhome/work
      - /docker/adguardhome/conf:/opt/adguardhome/conf
    ports:
      # Plain DNS
      - 53:53/tcp
      - 53:53/udp

      # DHCP server
      - 67:67/udp
      - 68:68/tcp
      - 68:68/udp

      # Admin panel & DNS over HTTPS
      - 80:80/tcp
      - 443:443/tcp
      - 443:443/udp
      # - 3000:3000/tcp for initial setup only

      # DNS over TLS
      - 853:853/tcp

      # DNS over QUIC
      - 784:784/udp 
      - 8853:8853/udp
      - 853:853/udp

      # DNSCrypt server
      - 5443:5443/tcp
      - 5443:5443/udp

    image: adguard/adguardhome
